name: CAPO image build

on:
  schedule:
    - cron: '30 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-1804

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install qemu-kvm libvirt-bin qemu-utils    
    - name: Install prerequisites
      run: cd image-builder/images/capi && make deps-qemu
    - name: Build images
      run: make build-qemu-ubuntu-1804
