name: CAPO image build

on:
  schedule:
    - cron: '30 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt update && sudo apt install qemu-kvm libvirt-bin qemu-utils    
    - name: Build images
      run: cd images/capi && make build-qemu-ubuntu-1804
